# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpBreaker < Formula
  desc "Semantic MCP circuit breaker proxy for AI agent tool loops"
  homepage "https://github.com/shunvel/mcp-breaker"
  version "0.2.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shunvel/mcp-breaker/releases/download/v0.2.1/mcp-breaker_0.2.1_darwin_amd64.tar.gz"
      sha256 "861fb2c968ecbd8d28e3f67ea304ad0fa06cba03f878bdc9c6fd4b53fc9218d0"

      define_method(:install) do
        bin.install "mcp-breaker"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shunvel/mcp-breaker/releases/download/v0.2.1/mcp-breaker_0.2.1_darwin_arm64.tar.gz"
      sha256 "d73b8160b4456ee4bf569b62ed6f4a2bc882e8bbdbb904f2b3fc0f06b037c8f2"

      define_method(:install) do
        bin.install "mcp-breaker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shunvel/mcp-breaker/releases/download/v0.2.1/mcp-breaker_0.2.1_linux_amd64.tar.gz"
      sha256 "70d0937397b9684f0de6f40db3c509b167d5b2d71b81ebe9c5de4c5af30f60a8"
      define_method(:install) do
        bin.install "mcp-breaker"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shunvel/mcp-breaker/releases/download/v0.2.1/mcp-breaker_0.2.1_linux_arm64.tar.gz"
      sha256 "00839aaff9b56face06b54a93df532b9f335f5b08fc8d08d23bb6df8d2d28976"
      define_method(:install) do
        bin.install "mcp-breaker"
      end
    end
  end

  def caveats
    <<~EOS
      Semantic embeddings require the ONNX model cache:
        mcp-breaker models download

      For production semantic tracking install onnxruntime (e.g. brew install onnxruntime),
      or set MCP_BREAKER_MOCK_EMBED=1 for development without ONNX.
    EOS
  end

  test do
    assert_match "mcp-breaker", shell_output("#{bin}/mcp-breaker help", 2)
  end
end
